### ISSUE TITLE
Sequence Diagram 

### ISSUE THREAD

**Issue by elkahanna** [elkahanna/spektra-adhya-prasarana#10]
sequence diargam kan dilihat dari kodingannya kan ya?
kayak nama_metode
kan kalau klik menu peminjman berarti manggil "initilize url" kayak sequence kang dimas gningan 
nah aku mau ngikutin gto tpi  belum paham alur koding semuanya baru ngeh yg dosave, initilize 
kang dimas ada blognya penjelasan kodingannya?
nuhun seacanna kang 

 maaf kalau ga ngeh maksudnya ini juga binggung gimana ngejlasin maksud yg mau ditanyain

**Comment by dimMaryanto93** [comment]
gak usah ikutin cara saya, pake yang biasa jaa yang elka paham, toh sequance gak diliat ini

**Comment by dimMaryanto93** [comment]
ok atau mungkin hari rabu kita meeting lagi sekalian saya bantuin buat sequance.a

**Comment by elkahanna** [comment]
soalnya kata ibu annisa th kmrin bilang manggil fungsi gto

**Comment by elkahanna** [comment]
oke deh siap kang rabu jam 9?

**Comment by dimMaryanto93** [comment]
ok boleh jam 9, biasa ya diperpus.
