### ISSUE TITLE
seqeunce diagram

### ISSUE THREAD

**Issue by elkahanna** [elkahanna/spektra-adhya-prasarana#12]
![diusulkan](https://cloud.githubusercontent.com/assets/17589246/16729234/4fe67e5e-4795-11e6-8466-b39f2b84ca19.jpg)

sequence diagram kayak gni kang bner ga? kalau aku ngikuti kang dimas aku belum ngeh jadi aku masukin yang aku ngeh dlu

**Comment by dimMaryanto93** [comment]
ia itu udah bener

**Comment by elkahanna** [comment]
gapapa kan ya yang penting ada controllernya kan ya

**Comment by dimMaryanto93** [comment]
ia yang penting mah jadi user berinteraksinya sama boundary, nah si boundary nya itu bernteraksi ke controller trus controllernya itu bisa memanggil fungsi atau manggil class lain contohnya seperti itu manggil entity atau controller lainnya

**Comment by elkahanna** [comment]
![sequence angsuran prestasi](https://cloud.githubusercontent.com/assets/17589246/16797075/0bb364b4-4910-11e6-8280-806a7dad321d.jpg)
![sequence pembayaran](https://cloud.githubusercontent.com/assets/17589246/16797096/210f8c98-4910-11e6-8f00-98c0d856d979.jpg)

gimana kang

**Comment by dimMaryanto93** [comment]
ia udah ok

**Comment by elkahanna** [comment]
ada yang berplu diperbaiki ga kang 
yang dari fxml ke controllernya?

**Comment by elkahanna** [comment]
yang set dan get nya ?

**Comment by dimMaryanto93** [comment]
gak perlu udah biarin gitu ja, kalo menurut saya sih itu udah bener

**Comment by elkahanna** [comment]
oke ath kang nuhun
