### ISSUE TITLE
lap kasbon semua karyawan

### ISSUE THREAD

**Issue by dimMaryanto93** [elkahanna/spektra-adhya-prasarana#14]
![423outputdaftarkasbonbulan](https://cloud.githubusercontent.com/assets/13976658/17462198/58a60d44-5ccf-11e6-9078-bcd1d7954a5d.png)

gimana gitu bukan?

**Comment by elkahanna** [comment]
Tambahin tanggal pinjamanna kang

**Comment by dimMaryanto93** [comment]
lah gimana caranya itu khan bukan satu persatu?
