### ISSUE TITLE
Error Gender

### ISSUE THREAD

**Issue by muhamadhanifmuhsin** [elkahanna/spektra-adhya-prasarana#2]
Itu jenis kelamin blum bisa.. salah dimananya yaa?
Modul Employee
Class EmployeeFormController

**Comment by dimMaryanto93** [comment]
belum bisa gimana? gak tampil di combobox?

**Comment by muhamadhanifmuhsin** [comment]
combobox?

**Comment by muhamadhanifmuhsin** [comment]
RadioButton Jenis Kelamin dim.. valuenya ga masuk database

**Comment by dimMaryanto93** [comment]
ok

**Comment by dimMaryanto93** [comment]
![insert-jeniskelamin](https://cloud.githubusercontent.com/assets/13976658/15148281/b640540e-16ee-11e6-88d2-3a7a3573f3c4.png)

udah bisa, cuman belum saya push bentar ya saya rapihin dulu kodingnya

**Comment by muhamadhanifmuhsin** [comment]
ok

**Comment by dimMaryanto93** [comment]
udah saya push, drop dulu databsenya trus buat lagi ada perubahan entity
