### ISSUE TITLE
Uang Prestasi

### ISSUE THREAD

**Issue by dimMaryanto93** [elkahanna/spektra-adhya-prasarana#4]
untuk sistem uang prestasi klo saya baca dari draft elka gini bukan?
jadi contohnya saya karyawan yang udah lebih dari 2 tahun trus saya mau ngajuin motor misalnya ninja trus kurang lebih ex: form nya gini?

![422formpengajuankreditmotor](https://cloud.githubusercontent.com/assets/13976658/15464795/7deea3a0-20fb-11e6-9050-88d38397150f.png)

trus nanti di cek sama direktru distujui gak klo disteujui trus dikasih ex: form nya kayak gini

![422formpersetujuankreditmotor](https://cloud.githubusercontent.com/assets/13976658/15464825/9fc190d2-20fb-11e6-8917-71566a4db1f2.png)

trus nanti untuk formnya pembayaran cicilan motornya biasa cuman pilih motor trus masukin nominalnya?

**Comment by elkahanna** [comment]
iya kurang lebih kayak gto kang

**Comment by dimMaryanto93** [comment]
ok sip

**Comment by dimMaryanto93** [comment]
oh ia, satu lagi kadi uang prestasi itu cuman bisa 1 motor untuk 1 karyawan?

**Comment by elkahanna** [comment]
yg ngajuin itu bagian keuangannya kan bukan karyawannya, jadi bagian keuangan yg ngajuin ke direktur nnti karyawannya suruh milih mau motor apa yg diambil

**Comment by dimMaryanto93** [comment]
oh ok sip :+1:

**Comment by elkahanna** [comment]
iya kang jadi kayak reward buat kryawan tersebut

**Comment by elkahanna** [comment]
form diatas th untuk form direktur nya kang?

**Comment by elkahanna** [comment]
kang kayaknya besok ga bisa ketmu jam 9 soalnya aku masuk pak rajab jam 10...

**Comment by dimMaryanto93** [comment]
ok, ok gpp next time aja

**Comment by dimMaryanto93** [comment]
oh ia brati motornya dicariin sama perusahaan, that mean -> bagian keuangan yang nyariin motor buat karyawannya?

**Comment by dimMaryanto93** [comment]
yang pengajuan buat keuangan yang persetujuan buat direktur ato karyawan nya juga biasa jadi ada perstujuan antara 2 belah pihak

**Comment by dimMaryanto93** [comment]
trus klo saya liat lagi pembayarannya mau dibarengin sama pas gajian atu form terpisah?

**Comment by elkahanna** [comment]
rabu aja gimana kang ?

**Comment by elkahanna** [comment]
iya motor yg dipilih sama karyawan nnti dipesanin sama bagian keuangan

**Comment by elkahanna** [comment]
hehee maaf kan "yang pengajuan buat keuangan yang persetujuan buat direktur ato karyawan nya juga biasa jadi ada perstujuan antara 2 belah pihak"
maksudnya gimana ?

**Comment by elkahanna** [comment]
pembayaran angsuran mksdnya ?
disatuin kang soalnya di datanya uang prestasi diberikan breng sama penggajiannya 
nah kalau untuk form prestasi, formnya dipisah

**Comment by dimMaryanto93** [comment]
oh ia saya lupa karyawan gak make software khan ya? jadi cuman direktur ja yang melakukan persetujuan

**Comment by dimMaryanto93** [comment]
pembayaran angsuran motor, jadi khan dp mah dibayar pertama kali setiap motor mungkin bisa beda meskipun motornya sama jadi setau saya tergantung dari krediturnya. klo pembayaran angsurannya khan klo diliat lagi dari lampirannya itu disatuin sama penggajian tpi gak tau juga sih soalnya klo diliat rada aneh juga

**Comment by dimMaryanto93** [comment]
ok hari rabu saya free

**Comment by dimMaryanto93** [comment]
oh ia klo pembayaran uang mukanya itu kapan? apa pas udah disteujui langsung dikasih uangnya tau pas gajian?

**Comment by elkahanna** [comment]
kang itu yang pinjman karyawan yang cek saldo kan itu harusnya ada nominalnya kan ya?

**Comment by elkahanna** [comment]
oh iya kang kan dilaporan th ada implemntasi basis datanya nah itu kan ngambil dari databse, nah aku ngmbil databasenya gimana?

**Comment by dimMaryanto93** [comment]
nominal gimana?
, ia tinggal di export ja ke sql lin

**Comment by dimMaryanto93** [comment]
untuk export ke sqlnya bisa pake CMD / terminal 

[baca disini](https://www.postgresql.org/docs/current/static/app-pgdump.html)

**Comment by elkahanna** [comment]
yg dipinjaman kan ada tu "cek saldo"  itu kan ada mksdnya saldo pinjmanan karyawan kan?

**Comment by elkahanna** [comment]
oh iya kang

**Comment by dimMaryanto93** [comment]
oh itu jadi nanti nampilin daftar saldo klo gak salah, tpi itu baru rencana doank sih belum bikin fungsinya

**Comment by dimMaryanto93** [comment]
cara export ke sql, ini saya udah buat artikelnya [check this out](http://dimmaryanto.github.io/blog/software/database/postgresql/pg_dump-export-sql/)

**Comment by dimMaryanto93** [comment]
- keterangan kelebihan / kekurangan angsuran :white_check_mark: 
- keterangan kelebihan uang muka (DP)

**Comment by dimMaryanto93** [comment]
![pembayaran](https://cloud.githubusercontent.com/assets/13976658/16935518/4cd972d4-4d8a-11e6-8193-b0852411c8d0.png)

gimana klo kayak gini untuk yang uang muka? jadi khan klo uang muka dicairkannya pas disetujuai dan bukan di penggajian jadi rada bingung klo dibuat kyaka untuk pembayaran angsuran mah.

jadi saya cuman kasih text aja. klo lebih dari Rp 3 jt maka sisa.a menjadi tangggung jawab karyawan
