### ISSUE TITLE
Penggajian

### ISSUE THREAD

**Issue by dimMaryanto93** [elkahanna/spektra-adhya-prasarana#5]
klo penggajian kayak.a mending satu" deh soalnya kemungkinan khan diambilnya mungkin bisa gak berbarengan kecuali klo emang udah dari perusahaanya nerima gaji itu serentak?

**Comment by dimMaryanto93** [comment]
Pembayaran cicilan motor klo lebih dari Rp500.000,- potong gaji ex:

GajiPokok = 1.500.000
cicilan = 600.000

kelebihanCicilan -> cicilan - 500.000 = 600.000
                                                          =  100.000
maxCicilan -> icicilan - kelebihanCicilan = 600.000 - 100.000
                                                               = 500.000

**Comment by dimMaryanto93** [comment]
![penggajian-karyawan](https://cloud.githubusercontent.com/assets/13976658/16105931/d25581cc-33b9-11e6-9058-6add7e7e7fb3.png)

Untuk penggajian gimana klo kayak gini?

jadi potongan gaji pokoknya pas pencairan dana gaji karyawan

**Comment by elkahanna** [comment]
iya gto kang 
keterangannya mah nnti aja aku terangin pas presentasi aja kali ya... ga usah dicantumin dalam sistemnya?

**Comment by dimMaryanto93** [comment]
ok nanti siang saya tambahin keterangannya di pengajuan angsuran

**Comment by elkahanna** [comment]
sip kang

**Comment by dimMaryanto93** [comment]
gimana klo yang notifikasi angsuran prestasi di penggajuannya kayak gini. jadi pas pengajuannya cuman ada ketarnagan aj nanti pas penggajiannya khan ada potongan gajinya gimana?

![notif](https://cloud.githubusercontent.com/assets/13976658/16215623/0bd8902e-378e-11e6-84ef-2fd969535cf5.png)
