### ISSUE TITLE
Kasbon atau peminjaman karyawan

### ISSUE THREAD

**Issue by dimMaryanto93** [elkahanna/spektra-adhya-prasarana#6]
gimana klo kayak gini rancangannya jadi alurnya adalah 
- Pengajuan peminjaman / kasbon karyawan

![422formpengajuanpeminjamankaryawan](https://cloud.githubusercontent.com/assets/13976658/15682250/006d5a60-2787-11e6-9f72-9a91528724f5.png)
- Persetujuan peminjaman / kasbon karyawan

![422formpersetujuanpeminjamankaryawan](https://cloud.githubusercontent.com/assets/13976658/15682262/0c5b2a28-2787-11e6-9229-7b8909554b29.png)
- Pembayaran peminjaman / kasbon karyawan

![422formpembayaranpeminjamankaryawan](https://cloud.githubusercontent.com/assets/13976658/15682284/25ec66dc-2787-11e6-8505-4f9a4e1f3abf.png)

**Comment by elkahanna** [comment]
oke sip kang

**Comment by dimMaryanto93** [comment]
sip, insyaaloh nanti sore beres untuk modul ini.

**Comment by elkahanna** [comment]
ooh iya kang untuk daftar uang prestasi itu cuma lihat bias lihat aja ? kang bias nginputin?

**Comment by dimMaryanto93** [comment]
klo yang daftar uang prestasi itu cuman liat aja gak bisa nginput

**Comment by elkahanna** [comment]
nah kalau misalkan dia mau mneginputkan pembyaran angsuraannya gimana kang ? jadi buat bukti gito angsuran ke berpaa

**Comment by dimMaryanto93** [comment]
ok nanti ya saya lagi buat ulang yang kasbon karyawan dulu

**Comment by dimMaryanto93** [comment]
oh nanti komennya sesuai dengan title supaya gak lier campur" kayak gini

**Comment by elkahanna** [comment]
oh iya kang maaf

**Comment by dimMaryanto93** [comment]
## Alurnya
- bagian keuangan input peminjamankan

![pengajuan](https://cloud.githubusercontent.com/assets/13976658/15718376/422501fa-2855-11e6-9fea-859591fefd28.png)
- direktur melakukan persetujuan

![persetujuan-direktur](https://cloud.githubusercontent.com/assets/13976658/15718400/54b4d6a6-2855-11e6-8c1a-344262a14659.png)
- setelah disetujui balik lagi ke bagian keuangan memberikan dana ke karyawan

![pencairan-dana](https://cloud.githubusercontent.com/assets/13976658/15718419/6631d01e-2855-11e6-885a-1843e27fd824.png)
- setelah itu melakukan pembayaran

![pembayaran-kasbon](https://cloud.githubusercontent.com/assets/13976658/15718423/6f465ea4-2855-11e6-8d9b-d1f2a8ca8f87.png)
- kemudian ini laporan keuangannya

![laporan-keuangan-kasbon](https://cloud.githubusercontent.com/assets/13976658/15718436/7aaa396e-2855-11e6-9f2f-f5e0a1692ebe.png)

gimana?

**Comment by elkahanna** [comment]
kang dimas, untuk yang peminjaman gimana kalau kita memotong gaji aja tapi untuk meminjman diatas 10 juta
soalnya di spektra kalau peminjaman besar memotong thr/ bonus tahunan sedangan bonus tahunan ga aku masukin da soalnya takut ga keburu waktunya 
gimana kang? kata bu tutinya mah terserah atur" aja

**Comment by dimMaryanto93** [comment]
karyawan yang bisa melakukan peminjaman hanya karyawan yang sudah bekerja selama lebih dari 1 tahun

**Comment by dimMaryanto93** [comment]
kalo karyawan keluar, semua tunggakan harus dilunasi dulu

**Comment by dimMaryanto93** [comment]
Tambah cetak pengajuan kasbon karyawanan

**Comment by dimMaryanto93** [comment]
- label peminjaman kasbon karyawan -> kwitansi peminjaman
- tanggal transaksi
- jabatan
- tanda tangan
