### ISSUE TITLE
Laporan penggajian karyawan

### ISSUE THREAD

**Issue by dimMaryanto93** [elkahanna/spektra-adhya-prasarana#8]
### Daftar penggajian karyawan
- fxml :white_check_mark: 
- jasper :white_check_mark: 

![423outputdaftargajikaryawanperbulan](https://cloud.githubusercontent.com/assets/13976658/15812282/3761a09e-2bdd-11e6-9317-caeedefec06a.png)
### Kwitansi setiap karyawan / slip gaji
- jasper (tampilkan setelah menerima penggajian) :white_check_mark: 

![423outputgajiperkaryawan](https://cloud.githubusercontent.com/assets/13976658/15812331/b1c279e4-2bdd-11e6-9a35-ab0aff4192a3.png)

**Comment by dimMaryanto93** [comment]
## Laporan daftar gaji karyawan

![laporan-daftar-gaji](https://cloud.githubusercontent.com/assets/13976658/15829725/2a937f38-2c3f-11e6-89f3-65b8ad43b73b.png)

gimana? ada tambahan?

**Comment by elkahanna** [comment]
semntara mah itu dulu we kang kata aku mah udah cukup sesuai dengan datanya, tapi coba nnti sya bimbingan apa kata ibu annisanya

**Comment by dimMaryanto93** [comment]
ok

**Comment by elkahanna** [comment]
nuhun kang, aku mau bikin issue tapi lupa caranya new repository dlu ?

**Comment by dimMaryanto93** [comment]
oh ia klo mau coba yang udah ada laporannya pilih brach yang development ya

![development-braches](https://cloud.githubusercontent.com/assets/13976658/15830049/9ded5cb4-2c40-11e6-9fe3-5c6ee7b92f08.png)

klo udak kepilih braches development baru download ke zip

**Comment by dimMaryanto93** [comment]
klo mau bikin issues pilih dulu repositorynya, klo gak mah ke url http://github.com/elkahanna/spektra-adhya-prasarana/issues

**Comment by dimMaryanto93** [comment]
ini hasil cetak untuk slip gaji perkayawan

![wp_20160607_001](https://cloud.githubusercontent.com/assets/13976658/15846486/c810b592-2ca7-11e6-813f-3bc7723455fe.jpg)

gimana ok?

**Comment by dimMaryanto93** [comment]
ini hasil cetak untuk daftar gaji karyawan

![wp_20160607_003](https://cloud.githubusercontent.com/assets/13976658/15852192/78d8c19a-2cca-11e6-97a3-d73fff521dec.jpg)

**Comment by dimMaryanto93** [comment]
Tambahkan field angsuran presasi di total
